### ISSUE TITLE
Why maps for options?

### ISSUE THREAD

**Issue by minijackson** [arvidkahl/sizeable#2]
Why are you using maps to specify options within the parameters? It seems to me that keyword lists are more Elixir-y ^^

Plus, you could do:
```elixir
Sizeable.filesize(1024, bits: true)
```

which is clearer in my opinion.

If you want to switch to keyword lists, you would just have to change this
```elixir
Map.get(options, :my_option, default_value)
```
in your code by:
```elixir
Keyword.get(options, :my_option, default_value)
```
(and some other minor changes)

Also instead of defining the function `filesize` with 1 argument, you could use a default argument (`filesize(value, options \\ %{})` if you use a map), but that's still your choice.

Sorry if I might have sounded a bit pushy

**Comment by arvidkahl** [comment]
Thanks, I will refactor the library to use Keyword Lists as you recommend. I wanted to bump it to 1.0 anyway, so that might be a good change to do it for.

**Comment by arvidkahl** [comment]
Finally finished that, it's all in b5fac2ee27854878f4e3e91daa55b159c411945b.
